### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by BMOv2600** [tcarlsen/atom-csslint#14]
I can't really tell what steps it would take to reproduce this error. It happened just as I was saving one css file and opening another. I'll add more details if it happens again.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [csslint](https://github.com/tcarlsen/atom-csslint) package, v1.1.3

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65

TypeError: Invalid Point: (NaN, 0)
  at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:970:13)
  at MarkerStore.module.exports.MarkerStore.setMarkerRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:307:29)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:325:20)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:143:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:175:32)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:136:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:733:7)
  at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:134:19)
  at [object Object].LineMessageView.goToLine (/Users/BMOre/.atom/packages/csslint/node_modules/atom-message-panel/lib/LineMessageView.js:60:53)
  at HTMLDivElement.<anonymous> (/Users/BMOre/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLDivElement.jQuery.event.dispatch (/Users/BMOre/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Users/BMOre/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -2:26.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:24.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:24.2.0 autoprefixer (atom-text-editor.editor)
  2x -2:01.1.0 core:undo (atom-text-editor.editor.is-focused)
     -1:36.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:33.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:33.9.0 autoprefixer (atom-text-editor.editor)
  2x -1:10.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:49.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:47.2.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:44.3.0 core:save-as (atom-text-editor.editor.is-focused)
     -0:31.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:29.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:27.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:25.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.6.0 autoprefixer (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "zenburn"
    ],
    "disabledPackages": [
      "webbox-color",
      "csscomb",
      "css-comb",
      "linter-csslint",
      "gulp-helper",
      "gulp-snippets"
    ],
    "projectHome": "~/Users/BMOre/Desktop/bmo/my_site/wp-content/themes/influence-child",
    "audioBeep": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-material-ui, v0.5.13
atom-minify, v0.2.2
auto-indent, v0.5.0
autoprefixer, v2.2.4
bezier-curve-editor, v0.7.2
browser-plus, v0.0.34
color-picker, v2.0.11
csslint, v1.1.3
editorconfig, v1.0.1
file-icons, v1.6.3
highlight-line, v0.11.0
indent-guide-improved, v1.4.1
linter, v1.3.4
linter-js-standard, v2.4.0
linter-jshint, v1.1.5
linter-php, v1.0.3
navigate, v0.1.10
php-debug, v0.1.2
pigments, v0.9.3
project-manager, v1.15.11
tab-control, v0.6.7
tool-bar, v0.1.8
tool-bar-main, v0.0.8
white-cursor, v0.6.0
zenburn, v3.0.0

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
this is a problem in [atom-message-panel](tcarlsen/atom-message-panel), that comes up sometimes then trying to click gotoline.

Im aware of this and testing it, thx for reporting :smile: 

going to close this issue, because there is nothing I can do inside this repo
