### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by JoeyQiang** [tcarlsen/atom-csslint#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [csslint](https://github.com/tcarlsen/atom-csslint) package, v1.1.4

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at module.exports (/Users/Joey/.atom/packages/csslint/lib/config.coffee:6:43)
    at /Users/Joey/.atom/packages/csslint/lib/linter.coffee:20:48
    at exports.allowUnsafeEval (/Users/Joey/.atom/packages/csslint/node_modules/loophole/lib/loophole.js:14:14)
    at module.exports (/Users/Joey/.atom/packages/csslint/lib/linter.coffee:20:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1104:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1074:19)
    at RemoteEditEditor.module.exports.RemoteEditEditor.save (/Users/Joey/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:65:15)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:43.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:43.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:22 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:17.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:07.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.27
autocomplete-php, v0.3.7
csslint, v1.1.4
emmet, v2.3.13
file-icons, v1.6.13
highlight-line, v0.11.0
javascript-snippets, v1.0.0
minimap, v4.16.2
php-cs-fixer, v2.5.6
remote-edit, v1.8.24

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
should be fixed in 1.1.5
