### ISSUE TITLE
Failed to load the csslint package

### ISSUE THREAD

**Issue by gaolaozhuang** [tcarlsen/atom-csslint#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [csslint](https://github.com/tcarlsen/atom-csslint) package 1.1.5

### Stack Trace

Failed to load the csslint package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-csslint/lib/linter.coffee:1:57)
    at /packages/atom-csslint/lib/linter.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-csslint/lib/main.coffee:1:10)
    at /packages/atom-csslint/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
```

### Commands

```
     -1:02.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
file-icons 2.0.15 
autoprefixer 3.6.1 
atom-beautify 0.29.17 
csslint 1.1.5 
atom-ctags 5.0.0 
atom-html-preview 0.1.22 
jshint 1.8.6 
script 3.14.1 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.54 
color-picker 2.2.5 
docblockr 0.9.1 
emmet 2.4.3 
git-plus 7.3.0 
java-importer 1.4.0 
merge-conflicts 1.4.4 
python-tools 0.6.9 
sync-settings 0.8.1 
vim-mode 0.66.0 
```

**Comment by tcarlsen** [comment]
looks like the installation of the package failed to install atom-message-panel. 

Try removing and reinstalling the package
