### ISSUE TITLE
Failed to activate the csslint package

### ISSUE THREAD

**Issue by Idrees-Mo** [tcarlsen/atom-csslint#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [csslint](https://github.com/tcarlsen/atom-csslint) package 1.2.0

### Stack Trace

Failed to activate the csslint package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146461)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/csslint/lib/linter.coffee:2:10)
    at /packages/csslint/lib/linter.coffee:1:1)
    at /packages/csslint/lib/linter.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/csslint/lib/main.coffee:1:10)
    at /packages/csslint/lib/main.coffee:1:1)
    at /packages/csslint/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017448)
```

### Commands

```
     -4:58.9.0 core:paste (input.hidden-input)
     -3:11.9.0 core:backspace (input.hidden-input)
     -3:10.6.0 core:paste (input.hidden-input)
     -2:34.8.0 core:delete (input.hidden-input)
  2x -2:33.8.0 core:paste (input.hidden-input)
     -1:47.5.0 core:delete (input.hidden-input)
     -1:46.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.18.3 
csslint 1.2.0 
emmet 2.4.3 
linter 2.3.0 
```

**Comment by tcarlsen** [comment]
Hey

Im really not maintaining this package anymore, after the [Linter](https://atom.io/packages/linter) came to live and took all linting packages. 

If you still want to use this package and want to help, I will gladly accept a PR
