### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by uanwar88** [tcarlsen/atom-csslint#9]
[Enter steps to reproduce below:]

1. ... Saved my CSS document.
2. ... Tried to close the CSSLinter window by clicking on 'X'.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.9
**Thrown From**: [csslint](https://github.com/tcarlsen/atom-csslint) package, v1.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'data' of undefined

```
At /Users/usman/.atom/packages/csslint/node_modules/atom-message-panel/lib/MessagePanelView.js:206

TypeError: Cannot read property 'data' of undefined
  at [object Object].MessagePanelView.resizeStopped (/Users/usman/.atom/packages/csslint/node_modules/atom-message-panel/lib/MessagePanelView.js:206:6)
  at [object Object].MessagePanelView.close (/Users/usman/.atom/packages/csslint/node_modules/atom-message-panel/lib/MessagePanelView.js:108:12)
  at HTMLDivElement.<anonymous> (/Users/usman/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLDivElement.jQuery.event.dispatch (/Users/usman/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Users/usman/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -1:17.3 editor:newline (atom-text-editor.editor)
  3x -1:14.0 core:backspace (atom-text-editor.editor)
     -1:12.7 core:save (atom-text-editor.editor)
     -1:10.2 core:delete (atom-text-editor.editor)
     -1:08.9 core:save (atom-text-editor.editor)
     -1:03.9 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:03.9 editor:newline (atom-text-editor.editor.is-focused)
     -1:00.2 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:00.2 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:59.5 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:56.4 autocomplete-plus:select-next (atom-text-editor.editor.is-focused)
  4x -0:54.1 autocomplete-plus:select-previous (atom-text-editor.editor.is-focused)
     -0:53.1 autocomplete-plus:select-next (atom-text-editor.editor.is-focused)
  2x -0:50.8 core:backspace (atom-text-editor.editor.is-focused)
     -0:49.6 core:save (atom-text-editor.editor.is-focused)
     -0:38.3 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "atom-erb"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.6
color-picker, v1.4.4
csslint, v1.0.3
emmet-atom, v2.3.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by jyksnw** [comment]
I am seeing the same issue on Windows 8 Pro using Atom Version 0.179.0

[Enter steps to reproduce below:]

1. Saved CSS document
2. Attempted to navigate to my html document

**Atom Version**: 0.179.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [csslint](https://github.com/tcarlsen/atom-csslint) package, v1.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'data' of undefined

```
At C:\Users\Jason\.atom\packages\csslint\node_modules\atom-message-panel\lib\MessagePanelView.js:206

TypeError: Cannot read property 'data' of undefined
  at [object Object].MessagePanelView.resizeStopped (C:\Users\Jason\.atom\packages\csslint\node_modules\atom-message-panel\lib\MessagePanelView.js:206:6)
  at [object Object].MessagePanelView.close (C:\Users\Jason\.atom\packages\csslint\node_modules\atom-message-panel\lib\MessagePanelView.js:108:12)
  at C:\Users\Jason\.atom\packages\htmlhint\lib\linter.coffee:47:14
  at Emitter.module.exports.Emitter.emit (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\src\pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\src\pane.js:328:21)
  at tabs-tab.<anonymous> (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\node_modules\tabs\lib\tab-bar-view.js:189:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-ul.elemData.handle (C:\Users\Jason\AppData\Local\atom\app-0.179.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -2:36.8 editor:newline (atom-text-editor.editor)
  2x -2:36.1 core:backspace (atom-text-editor.editor)
     -2:34.1 core:move-down (atom-text-editor.editor)
     -2:33.5 core:move-up (atom-text-editor.editor)
  8x -2:32.5 core:backspace (atom-text-editor.editor)
     -2:12.4 core:copy (atom-text-editor.editor)
     -2:05.7 grammar-selector:show (atom-pane.pane.active)
     -2:02.1 core:save (ul.list-inline.tab-bar.inset-panel)
     -1:39.2 core:paste (atom-text-editor.editor)
     -1:37.4 core:backspace (atom-text-editor.editor)
     -1:36.9 core:save (atom-text-editor.editor)
     -1:25.7 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -1:25.7 editor:newline (atom-text-editor.editor)
     -1:24.3 editor:select-to-beginning-of-word (atom-text-editor.editor)
  6x -1:23.4 core:backspace (atom-text-editor.editor)
  2x -0:52.7 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.1.0
autoclose-html, v0.15.0
autocomplete-plus, v2.1.6
color-picker, v1.4.4
csslint, v1.0.3
editor-stats, v0.17.0
editorconfig, v0.3.0
emmet, v2.3.3
highlight-line, v0.9.3
htmlhint, v1.0.1
javascript-snippets, v1.0.0
jshint, v1.2.0

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
hmmm I cant reproduce the error. can one of you sent me the file coursing the error or does it happen to every css file you try?

**Comment by tcarlsen** [comment]
this looks like an AMP issue in the new `1.2.0` 
https://github.com/tcarlsen/atom-message-panel/issues/65

**Comment by tcarlsen** [comment]
this issue is fixed in AMP but I believe you need to reinstall csslint for the package to redownload to the new AMP version
